export default [
  { value: 'EMPLOYEE', text: 'Angestellte(r)' },
  { value: 'CONTACT_PERSON', text: 'Ansprechpartner' },
  { value: 'OFFICIAL', text: 'Beamte(r)' },
  { value: 'CONTROLLER', text: 'Controller/in' },
  { value: 'DIRECTOR', text: 'Direktor/in' },
  { value: 'COMPANY_CAR_DRIVER', text: 'Dienstwagennutzer/in' },
  { value: 'PURCHASE_TRUCK', text: 'Einkäufer/in LKW' },
  { value: 'PURCHASE_PC', text: 'Einkäufer/in PKW' },
  { value: 'DRIVER', text: 'Fahrer' },
  { value: 'FREELANCER', text: 'Freiberufl./Selbst.' },
  { value: 'MANAGING_DIRECTOR', text: 'Geschäftsführer/in' },
  { value: 'SHAREHOLDER', text: 'Gesellschafter/in' },
  { value: 'OWNER', text: 'Inhaber/in' },
  { value: 'MANAGER', text: 'Leit. Angestellte/r' },
  { value: 'FLEET_MANAGER_TRUCK', text: 'Leiter/in FUP LKW' },
  { value: 'FLEET_MANAGER_PC', text: 'Leiter/in FUP PKW' },
  { value: 'WORKSHOP_MANAGER', text: 'Leiter/in Werkstatt' },
  { value: 'EMPLOYEE_DAIMLER_NDL', text: 'Mitarbeiter/in NDL' },
  { value: 'MANAGING_DIRECTOR_DAIMLER_NDL', text: 'Leiter/in NDL' },
  { value: 'AUTHORIZED_OFFICER', text: 'Prokurist/in' },
  { value: 'PENSIONER', text: 'Rentner/in' },
  { value: 'SECRETARY', text: 'Sekretär/in' },
  { value: 'OTHER', text: 'Sonstige' },
  { value: 'STUDENT', text: 'Student/in' },
  { value: 'BOARD_MEMBER', text: 'Vorstandsmitglied' },
  { value: 'CEO', text: 'Vorstandsvorsitzende' },
  { value: 'DAIMLER_EMPLOYEE', text: 'Werksangehörige(r)' }
];
