// This is related to orderservice/order/printing/dto/PrintOrderDocumentOptions.kt
export const OPTIONS = {
  ORDER: 'ORDER',
  CHANGE_ORDER: 'CHANGE_ORDER',
  EVB: 'EVB',
  BESTELLUNG: 'ORDER',
  VERBRAUCHERINFORMATION: 'MB_VERBRAUCHERINFORMATION',
  WIDERRUFSBELEHRUNG: 'MB_WIDERRUFSBELEHRUNG',
  AGB: 'NEUFAHRZEUG_AGBS',
  SIGNATUR: 'SIGNATURE_PAGE',
  ABB: 'ABB'
};

export const ACTIONS = {
  DEFAULT_OPTIONS: 'DEFAULT_OPTIONS',
  SET_OPTION: 'SET_OPTION',
  ENABLE_EV: 'ENABLE_EV'
};
