export default [
  { value: 'DE', text: 'Deutschland' },
  { value: 'AD', text: 'Andorra' },
  { value: 'AE', text: 'Vereinigte Arabische Emirate' },
  { value: 'AF', text: 'Afghanistan' },
  { value: 'AG', text: 'Antigua und Barbuda' },
  { value: 'AI', text: 'Anguilla' },
  { value: 'AL', text: 'Albanien' },
  { value: 'AM', text: 'Armenien' },
  { value: 'AN', text: 'Niederländische Antillen' },
  { value: 'AO', text: 'Angola' },
  { value: 'AQ', text: 'Antarktis' },
  { value: 'AR', text: 'Argentinien' },
  { value: 'AS', text: 'Amerik. Samoa' },
  { value: 'AT', text: 'Österreich' },
  { value: 'AU', text: 'Australien' },
  { value: 'AW', text: 'Aruba' },
  { value: 'AX', text: 'Alandinseln' },
  { value: 'AZ', text: 'Azerbaijan' },
  { value: 'BA', text: 'Bosnien-Herzegowina' },
  { value: 'BB', text: 'Barbados' },
  { value: 'BD', text: 'Bangladesch' },
  { value: 'BE', text: 'Belgien' },
  { value: 'BF', text: 'Burkina Faso' },
  { value: 'BG', text: 'Bulgarien' },
  { value: 'BH', text: 'Bahrain' },
  { value: 'BI', text: 'Burundi' },
  { value: 'BJ', text: 'Benin' },
  { value: 'BM', text: 'Bermudas' },
  { value: 'BN', text: 'Brunei' },
  { value: 'BO', text: 'Bolivien' },
  { value: 'BR', text: 'Brasilien' },
  { value: 'BS', text: 'Bahamas' },
  { value: 'BT', text: 'Bhuta' },
  { value: 'BV', text: 'Bouvet Inseln' },
  { value: 'BW', text: 'Botswana' },
  { value: 'BY', text: 'Weißrussland' },
  { value: 'BZ', text: 'Belize' },
  { value: 'CA', text: 'Kanada' },
  { value: 'CC', text: 'Cocos (Keeling) Inseln' },
  { value: 'CD', text: 'Demokratische Republik Kongo' },
  { value: 'CF', text: 'Republik Zentral Afrika' },
  { value: 'CG', text: 'Kongo' },
  { value: 'CH', text: 'Schweiz' },
  { value: 'CI', text: 'Elfenbeinküste' },
  { value: 'CK', text: 'Cook Inseln' },
  { value: 'CL', text: 'Chile' },
  { value: 'CM', text: 'Kamerun' },
  { value: 'CN', text: 'China' },
  { value: 'CO', text: 'Kolumbien' },
  { value: 'CR', text: 'Costa Rica' },
  { value: 'CU', text: 'Kuba' },
  { value: 'CV', text: 'Kap Verde' },
  { value: 'CX', text: 'Weihnachtsinseln' },
  { value: 'CY', text: 'Zypern' },
  { value: 'CZ', text: 'Tschechische Republik' },
  { value: 'DJ', text: 'Djibouti' },
  { value: 'DK', text: 'Dänemark' },
  { value: 'DM', text: 'Dominika' },
  { value: 'DO', text: 'Dominikanische Republik' },
  { value: 'DZ', text: 'Algerien' },
  { value: 'EC', text: 'Ecuador' },
  { value: 'EE', text: 'Estland' },
  { value: 'EG', text: 'Ägypten' },
  { value: 'EH', text: 'West Sahara' },
  { value: 'ER', text: 'Eritrea' },
  { value: 'ES', text: 'Spanien' },
  { value: 'ET', text: 'Äthiopien' },
  { value: 'EU', text: 'EU' },
  { value: 'FI', text: 'Finnland' },
  { value: 'FJ', text: 'Fidschi' },
  { value: 'FK', text: 'Falkland Inseln' },
  { value: 'FM', text: 'Micronesien' },
  { value: 'FO', text: 'Faroer Inseln' },
  { value: 'FR', text: 'Frankreich' },
  { value: 'FX', text: 'Frankreich, Metropolitan' },
  { value: 'GA', text: 'Gabun' },
  { value: 'GB', text: 'Großbritannien' },
  { value: 'GD', text: 'Grenada' },
  { value: 'GE', text: 'Georgien' },
  { value: 'GF', text: 'Franz. Guiana' },
  { value: 'GH', text: 'Ghana' },
  { value: 'GI', text: 'Gibraltar' },
  { value: 'GL', text: 'Grönland' },
  { value: 'GM', text: 'Gambia' },
  { value: 'GN', text: 'Guinea' },
  { value: 'GP', text: 'Guadaloupe' },
  { value: 'GQ', text: 'Äquatorialguinea' },
  { value: 'GR', text: 'Griechenland' },
  { value: 'GS', text: 'Süd Georgia und die südlichen Sandwich Inseln' },
  { value: 'GT', text: 'Guatemala' },
  { value: 'GU', text: 'Guam' },
  { value: 'GW', text: 'Guinea-Bissau' },
  { value: 'GY', text: 'Guyana' },
  { value: 'HK', text: 'Hong Kong' },
  { value: 'HM', text: 'Heard und Mc Donald Inseln' },
  { value: 'HN', text: 'Honduras' },
  { value: 'HR', text: 'Kroatien' },
  { value: 'HT', text: 'Haiti' },
  { value: 'HU', text: 'Ungarn' },
  { value: 'ID', text: 'Indonesien' },
  { value: 'IE', text: 'Irland' },
  { value: 'IL', text: 'Israel' },
  { value: 'IM', text: 'Insel Man' },
  { value: 'IN', text: 'Indien' },
  { value: 'IO', text: 'Britisch-Indisch Ocean Territorium' },
  { value: 'IQ', text: 'Irak' },
  { value: 'IR', text: 'Iran' },
  { value: 'IS', text: 'Island' },
  { value: 'IT', text: 'Italien' },
  { value: 'JE', text: 'Gernsey-Kanalinsel' },
  { value: 'JM', text: 'Jamaica' },
  { value: 'JO', text: 'Jordanien' },
  { value: 'JP', text: 'Japan' },
  { value: 'KE', text: 'Kenia' },
  { value: 'KG', text: 'Kirgisistan' },
  { value: 'KH', text: 'Kambodscha' },
  { value: 'KI', text: 'Kiribati' },
  { value: 'KM', text: 'Comoros' },
  { value: 'KN', text: 'Sankt Kitts und Nevis' },
  { value: 'KP', text: 'Nord Korea' },
  { value: 'KR', text: 'Süd Korea' },
  { value: 'KW', text: 'Kuwait' },
  { value: 'KY', text: 'Kaimaninseln' },
  { value: 'KZ', text: 'Kazakhstan' },
  { value: 'LA', text: 'Laos' },
  { value: 'LB', text: 'Libanon' },
  { value: 'LC', text: 'Santa Lucia' },
  { value: 'LI', text: 'Liechtenstein' },
  { value: 'LK', text: 'Sri Lanka' },
  { value: 'LR', text: 'Liberia' },
  { value: 'LS', text: 'Lesotho' },
  { value: 'LT', text: 'Litauen' },
  { value: 'LU', text: 'Luxemburg' },
  { value: 'LV', text: 'Lettland' },
  { value: 'LY', text: 'Libyen' },
  { value: 'MA', text: 'Marokko' },
  { value: 'MC', text: 'Monaco' },
  { value: 'MD', text: 'Republik Moldawien' },
  { value: 'ME', text: 'Montenegro' },
  { value: 'MG', text: 'Madagascar' },
  { value: 'MH', text: 'Marshall Inseln' },
  { value: 'MK', text: 'Mazedonien' },
  { value: 'ML', text: 'Mali' },
  { value: 'MM', text: 'Myanmar' },
  { value: 'MN', text: 'Mongolei' },
  { value: 'MO', text: 'Macao' },
  { value: 'MP', text: 'Mariannen' },
  { value: 'MQ', text: 'Martinique' },
  { value: 'MR', text: 'Mauretanien' },
  { value: 'MS', text: 'Montserrat' },
  { value: 'MT', text: 'Malta' },
  { value: 'MU', text: 'Mauritius' },
  { value: 'MV', text: 'Malediven' },
  { value: 'MW', text: 'Malawi' },
  { value: 'MX', text: 'Mexico' },
  { value: 'MY', text: 'Malaysia' },
  { value: 'MZ', text: 'Mosambik' },
  { value: 'NA', text: 'Namibia' },
  { value: 'NC', text: 'Neukaledonien' },
  { value: 'NE', text: 'Niger' },
  { value: 'NF', text: 'Norfolk Inseln' },
  { value: 'NG', text: 'Nigeria' },
  { value: 'NI', text: 'Nicaragua' },
  { value: 'NL', text: 'Niederlande' },
  { value: 'NO', text: 'Norwegen' },
  { value: 'NP', text: 'Nepal' },
  { value: 'NR', text: 'Nauru' },
  { value: 'NU', text: 'Niue' },
  { value: 'NZ', text: 'Neuseeland' },
  { value: 'OM', text: 'Oman' },
  { value: 'PA', text: 'Panama' },
  { value: 'PE', text: 'Peru' },
  { value: 'PF', text: 'Franz. Polynesien' },
  { value: 'PG', text: 'Papua Neu Guinea' },
  { value: 'PH', text: 'Philippinen' },
  { value: 'PK', text: 'Pakistan' },
  { value: 'PL', text: 'Polen' },
  { value: 'PM', text: 'St.Pierre und Miquelon' },
  { value: 'PN', text: 'Pitcairn' },
  { value: 'PR', text: 'Puerto Rico' },
  { value: 'PS', text: 'Besetzte Palästinensische Gebiete' },
  { value: 'PT', text: 'Portugal' },
  { value: 'PW', text: 'Palau' },
  { value: 'PY', text: 'Paraguay' },
  { value: 'QA', text: 'Qatar' },
  { value: 'QQ', text: 'Schiffs- und Luftfahrzeugbedarf' },
  {
    value: 'QS',
    text: 'Schiffs- und Luftfahrzeugbedarf im Rahmen des Inne'
  },
  { value: 'QU', text: 'Nicht ermächtigte Länder und Gebiete' },
  { value: 'QV', text: 'Nicht ermächtigte Länder und Gebiete (EU)' },
  { value: 'QW', text: 'Nicht ermächtigte Länder und Gebiete (Drittland)' },
  { value: 'QX', text: 'Nicht nachgewiesene Länder und Gebiete' },
  { value: 'QY', text: 'Nicht nachgewiesene Länder und Gebiete (EU)' },
  {
    value: 'QZ',
    text: 'Nicht nachgewiesene Länder und Gebiete (Drittland)'
  },
  { value: 'RE', text: 'Reunion' },
  { value: 'RO', text: 'Rumänien' },
  { value: 'RS', text: 'Serbien' },
  { value: 'RU', text: 'Russland' },
  { value: 'RW', text: 'Ruanda' },
  { value: 'SA', text: 'Saudi Arabien' },
  { value: 'SB', text: 'Solomon Inseln' },
  { value: 'SC', text: 'Seychellen' },
  { value: 'SD', text: 'Sudan' },
  { value: 'SE', text: 'Schweden' },
  { value: 'SG', text: 'Singapur' },
  { value: 'SH', text: 'St. Helena' },
  { value: 'SI', text: 'Slowenien' },
  { value: 'SJ', text: 'Svalbard und die Jan Mayen Inseln' },
  { value: 'SK', text: 'Slowakei' },
  { value: 'SL', text: 'Sierra Leone' },
  { value: 'SM', text: 'San Marino' },
  { value: 'SN', text: 'Senegal' },
  { value: 'SO', text: 'Somalia' },
  { value: 'SR', text: 'Surinam' },
  { value: 'ST', text: 'Sao Tome/Principe' },
  { value: 'SV', text: 'El Salvador' },
  { value: 'SY', text: 'Syrien' },
  { value: 'SZ', text: 'Swaziland' },
  { value: 'TC', text: 'Turks und Caicos Inseln' },
  { value: 'TD', text: 'Tschad' },
  { value: 'TF', text: 'Franz. Süd-Territorium' },
  { value: 'TG', text: 'Togo' },
  { value: 'TH', text: 'Thailand' },
  { value: 'TJ', text: 'Tadschikistan' },
  { value: 'TK', text: 'Tokelau' },
  { value: 'TL', text: 'Timor-Leste' },
  { value: 'TM', text: 'Turkmenistan' },
  { value: 'TN', text: 'Tunesien' },
  { value: 'TO', text: 'Tonga' },
  { value: 'TP', text: 'Ost-Timor' },
  { value: 'TR', text: 'Türkei' },
  { value: 'TT', text: 'Trinidad und Tobago' },
  { value: 'TV', text: 'Tuvalu' },
  { value: 'TW', text: 'Taiwan' },
  { value: 'TZ', text: 'Tansania' },
  { value: 'UA', text: 'Ukraine' },
  { value: 'UG', text: 'Uganda' },
  { value: 'UM', text: 'Vereinigte Staaten Ozeanien' },
  { value: 'US', text: 'Vereinigte Staaten von Amerika' },
  { value: 'UY', text: 'Uruguay' },
  { value: 'UZ', text: 'Uzbekistan' },
  { value: 'VA', text: 'Vatikan Staat' },
  { value: 'VC', text: 'Sankt Vincent und die Grenadinen' },
  { value: 'VE', text: 'Venezuela' },
  { value: 'VG', text: 'Virgin Islands (brit.)' },
  { value: 'VI', text: 'Virgin Islands (U.S.)' },
  { value: 'VN', text: 'Vietnam' },
  { value: 'VU', text: 'Vanuatu' },
  { value: 'WF', text: 'Wallis und Futuna' },
  { value: 'WS', text: 'Samoa' },
  { value: 'XC', text: 'Ceuta' },
  { value: 'XK', text: 'Kosovo' },
  { value: 'XL', text: 'Melilla' },
  { value: 'YE', text: 'Jemen' },
  { value: 'YT', text: 'Mayotte' },
  { value: 'ZA', text: 'Südafrika' },
  { value: 'ZM', text: 'Sambia' },
  { value: 'ZR', text: 'Zaire' },
  { value: 'ZW', text: 'Simbabwe' }
];
